export function createWorldData({ rgb, vec2 }) {
  const WORLD_THEMES = Object.freeze({
    grassy: Object.freeze({
      id: "grassy",
      mapStyle: "grassy",
      levelStyle: "grassy",
      skyTop: rgb(82, 187, 255),
      skyBottom: rgb(135, 206, 235),
      grassTop: rgb(80, 220, 110),
      grassBottom: rgb(44, 178, 88),
      dirtTop: rgb(152, 110, 72),
      dirtBottom: rgb(118, 82, 52),
      hillLight: rgb(74, 210, 106),
      hillDark: rgb(54, 190, 92),
      pathActive: rgb(255, 255, 255),
      pathInactive: rgb(170, 170, 170),
      nodeOutline: rgb(20, 60, 28),
      nodeShadow: rgb(0, 0, 0),
      trainingDot: rgb(255, 214, 10),
      levelDot: rgb(52, 199, 89),
      textDark: rgb(16, 28, 20),
    }),
    desert: Object.freeze({
      id: "desert",
      mapStyle: "desert",
      levelStyle: "desert",
      skyTop: rgb(255, 205, 128),
      skyBottom: rgb(255, 238, 184),
      sandTop: rgb(243, 198, 112),
      sandBottom: rgb(226, 177, 90),
      duneLight: rgb(234, 186, 100),
      duneDark: rgb(212, 160, 78),
      pyramidLight: rgb(214, 162, 86),
      pyramidDark: rgb(188, 136, 68),
      sun: rgb(255, 234, 132),
      pathActive: rgb(115, 74, 28),
      pathInactive: rgb(170, 140, 110),
      nodeOutline: rgb(108, 70, 25),
      nodeShadow: rgb(40, 24, 8),
      trainingDot: rgb(255, 214, 10),
      levelDot: rgb(245, 156, 66),
      textDark: rgb(72, 46, 20),
    }),
    cloud: Object.freeze({
      id: "cloud",
      mapStyle: "cloud",
      levelStyle: "cloud",
      skyTop: rgb(90, 176, 232),
      skyBottom: rgb(146, 210, 244),
      cloudTop: rgb(252, 252, 255),
      cloudBottom: rgb(214, 234, 255),
      vine: rgb(74, 170, 92),
      pathActive: rgb(255, 255, 255),
      pathInactive: rgb(165, 190, 214),
      nodeOutline: rgb(54, 103, 138),
      nodeShadow: rgb(40, 74, 102),
      trainingDot: rgb(255, 214, 10),
      levelDot: rgb(116, 201, 255),
      textDark: rgb(29, 66, 92),
    }),
    space: Object.freeze({
      id: "space",
      mapStyle: "space",
      levelStyle: "space",
      skyTop: rgb(4, 9, 24),
      skyBottom: rgb(12, 18, 40),
      nebulaA: rgb(52, 70, 114),
      nebulaB: rgb(26, 38, 72),
      moonSurfaceLight: rgb(156, 164, 178),
      moonSurfaceDark: rgb(124, 132, 146),
      pathActive: rgb(222, 235, 255),
      pathInactive: rgb(102, 116, 148),
      nodeOutline: rgb(210, 220, 238),
      nodeShadow: rgb(0, 0, 0),
      trainingDot: rgb(255, 214, 10),
      levelDot: rgb(190, 214, 248),
      textDark: rgb(236, 242, 255),
    }),
    castle: Object.freeze({
      id: "castle",
      mapStyle: "castle",
      levelStyle: "castle",
      skyTop: rgb(24, 24, 34),
      skyBottom: rgb(36, 24, 22),
      lavaGlow: rgb(190, 76, 36),
      stoneLight: rgb(94, 98, 112),
      stoneDark: rgb(60, 64, 78),
      pathActive: rgb(255, 220, 190),
      pathInactive: rgb(124, 104, 98),
      nodeOutline: rgb(34, 34, 44),
      nodeShadow: rgb(0, 0, 0),
      trainingDot: rgb(255, 214, 10),
      levelDot: rgb(232, 140, 94),
      textDark: rgb(246, 232, 220),
    }),
  });

  const WORLD_MAPS = Object.freeze({
    world1: Object.freeze({
      id: "world1",
      title: "WORLD 1 — GRASSY AREA",
      themeId: "grassy",
      startLevelId: "training",
      nodes: Object.freeze([
        Object.freeze({
          levelId: "training",
          label: "T",
          kind: "training",
          pos: vec2(210, 344),
          requires: [],
        }),
        Object.freeze({
          levelId: "level1",
          label: "1",
          kind: "level",
          pos: vec2(548, 284),
          requires: ["training"],
          dotColor: WORLD_THEMES.grassy.levelDot,
        }),
        Object.freeze({
          levelId: "level2",
          label: "2",
          kind: "level",
          pos: vec2(792, 258),
          requires: ["level1"],
          dotColor: WORLD_THEMES.grassy.levelDot,
        }),
        Object.freeze({
          levelId: "castle1",
          label: "C",
          kind: "level",
          pos: vec2(884, 166),
          requires: ["level2"],
          dotColor: rgb(230, 230, 230),
        }),
      ]),
      connections: Object.freeze([
        Object.freeze({
          fromLevelId: "training",
          toLevelId: "level1",
          control: vec2(380, 220),
        }),
        Object.freeze({
          fromLevelId: "level1",
          toLevelId: "level2",
          control: vec2(680, 210),
        }),
        Object.freeze({
          fromLevelId: "level2",
          toLevelId: "castle1",
          control: vec2(860, 200),
        }),
      ]),
    }),
    world2: Object.freeze({
      id: "world2",
      title: "WORLD 2 — SCORCHED FRONTIER",
      themeId: "desert",
      startLevelId: "desert1",
      nodes: Object.freeze([
        Object.freeze({
          levelId: "desert1",
          label: "1",
          kind: "level",
          pos: vec2(164, 332),
          requires: ["boss1"],
          dotColor: WORLD_THEMES.desert.levelDot,
        }),
        Object.freeze({
          levelId: "desert2",
          label: "2",
          kind: "level",
          pos: vec2(324, 286),
          requires: ["desert1"],
          dotColor: WORLD_THEMES.desert.levelDot,
        }),
        Object.freeze({
          levelId: "desert3",
          label: "3",
          kind: "level",
          pos: vec2(496, 248),
          requires: ["desert2"],
          dotColor: WORLD_THEMES.desert.levelDot,
        }),
        Object.freeze({
          levelId: "desert4",
          label: "4",
          kind: "level",
          pos: vec2(660, 210),
          requires: ["desert3"],
          dotColor: WORLD_THEMES.desert.levelDot,
        }),
        Object.freeze({
          levelId: "desert5",
          label: "5",
          kind: "level",
          pos: vec2(812, 172),
          requires: ["desert4"],
          dotColor: WORLD_THEMES.desert.levelDot,
        }),
        Object.freeze({
          levelId: "boss2",
          label: "C",
          kind: "level",
          pos: vec2(902, 116),
          requires: ["desert5"],
          dotColor: rgb(245, 232, 210),
        }),
      ]),
      connections: Object.freeze([
        Object.freeze({
          fromLevelId: "desert1",
          toLevelId: "desert2",
          control: vec2(248, 292),
        }),
        Object.freeze({
          fromLevelId: "desert2",
          toLevelId: "desert3",
          control: vec2(412, 252),
        }),
        Object.freeze({
          fromLevelId: "desert3",
          toLevelId: "desert4",
          control: vec2(576, 214),
        }),
        Object.freeze({
          fromLevelId: "desert4",
          toLevelId: "desert5",
          control: vec2(740, 176),
        }),
        Object.freeze({
          fromLevelId: "desert5",
          toLevelId: "boss2",
          control: vec2(866, 138),
        }),
      ]),
    }),
    world3: Object.freeze({
      id: "world3",
      title: "WORLD 3 — CLOUD KINGDOM",
      themeId: "cloud",
      startLevelId: "cloud1",
      nodes: Object.freeze([
        Object.freeze({
          levelId: "cloud1",
          label: "1",
          kind: "level",
          pos: vec2(500, 274),
          requires: ["boss2"],
          dotColor: WORLD_THEMES.cloud.levelDot,
        }),
      ]),
      connections: Object.freeze([]),
    }),
    world4: Object.freeze({
      id: "world4",
      title: "WORLD 4 — MOON BASE",
      themeId: "space",
      startLevelId: "level-4-1",
      nodes: Object.freeze([
        Object.freeze({
          levelId: "level-4-1",
          label: "1",
          kind: "level",
          pos: vec2(500, 292),
          requires: ["cloud1"],
          dotColor: WORLD_THEMES.space.levelDot,
        }),
      ]),
      connections: Object.freeze([]),
    }),
    world5: Object.freeze({
      id: "world5",
      title: "WORLD 5 — INFERNAL STRONGHOLD",
      themeId: "castle",
      startLevelId: "castle5_1",
      nodes: Object.freeze([
        Object.freeze({
          levelId: "castle5_1",
          label: "1",
          kind: "level",
          pos: vec2(160, 326),
          requires: ["level-4-1"],
          dotColor: WORLD_THEMES.castle.levelDot,
        }),
        Object.freeze({
          levelId: "castle5_2",
          label: "2",
          kind: "level",
          pos: vec2(334, 286),
          requires: ["castle5_1"],
          dotColor: WORLD_THEMES.castle.levelDot,
        }),
        Object.freeze({
          levelId: "castle5_3",
          label: "3",
          kind: "level",
          pos: vec2(506, 250),
          requires: ["castle5_2"],
          dotColor: WORLD_THEMES.castle.levelDot,
        }),
        Object.freeze({
          levelId: "castle5_4",
          label: "4",
          kind: "level",
          pos: vec2(678, 214),
          requires: ["castle5_3"],
          dotColor: WORLD_THEMES.castle.levelDot,
        }),
        Object.freeze({
          levelId: "castle5_5",
          label: "5",
          kind: "level",
          pos: vec2(836, 176),
          requires: ["castle5_4"],
          dotColor: WORLD_THEMES.castle.levelDot,
        }),
        Object.freeze({
          levelId: "boss5",
          label: "C",
          kind: "level",
          pos: vec2(914, 120),
          requires: ["castle5_5"],
          dotColor: rgb(245, 236, 224),
        }),
      ]),
      connections: Object.freeze([
        Object.freeze({
          fromLevelId: "castle5_1",
          toLevelId: "castle5_2",
          control: vec2(250, 278),
        }),
        Object.freeze({
          fromLevelId: "castle5_2",
          toLevelId: "castle5_3",
          control: vec2(420, 248),
        }),
        Object.freeze({
          fromLevelId: "castle5_3",
          toLevelId: "castle5_4",
          control: vec2(592, 214),
        }),
        Object.freeze({
          fromLevelId: "castle5_4",
          toLevelId: "castle5_5",
          control: vec2(764, 176),
        }),
        Object.freeze({
          fromLevelId: "castle5_5",
          toLevelId: "boss5",
          control: vec2(890, 144),
        }),
      ]),
    }),
  });

  function worldIdForLevel(levelId) {
    if (typeof levelId !== "string") return "world1";
    for (const world of Object.values(WORLD_MAPS)) {
      if (world.nodes.some((n) => n.levelId === levelId)) return world.id;
    }
    return "world1";
  }

  return {
    WORLD_THEMES,
    WORLD_MAPS,
    worldIdForLevel,
  };
}
